# Week 4 · Day 1 — Exercises: NumPy Arrays & Central Tendency

Practice for array creation, attributes, reshaping, mean/median/mode, and array operations.

**How to work:**
- Fill in each cell where you see `...` or a `# TODO`.
- Run your cell and check the output makes sense before moving on.
- When finished: `Kernel → Restart & Run All`

Setup — run this first.

In [1]:
import numpy as np
import scipy as prob
np.random.seed(42)   # so everyone gets the same "random" numbers

---
## Part 1 — Creating arrays

**1.1** Create a NumPy array from the Python list `[3, 7, 11, 15, 19]`.

In [2]:
# TODO 1.1
arr = np.arange(3,20,4)
arr

array([ 3,  7, 11, 15, 19])

**1.2** Create a 2D array (a matrix) with these three rows: `[1,2,3]`, `[4,5,6]`, `[7,8,9]`.

In [3]:
# TODO 1.2  (hint: a list of lists)
mat = np.arange(1,10,1)
mat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
mat1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
matr=mat.reshape((3,3))

matr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**1.3** Use `np.arange` to create an array of all numbers from 10 to 50 (inclusive of 50).

In [6]:
# TODO 1.3  (careful: arange excludes the stop value)
arr50=np.arange(10,51,1)
arr50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
arr50.size

41

In [8]:
arr50.shape

(41,)

**1.4** Create an array of every **multiple of 5** from 5 to 100 (inclusive).

In [9]:
arrmult5=np.arange(5,101,5)
arrmult5

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

**1.5** Use `np.linspace` to create 9 evenly spaced numbers between 0 and 2.
*(How is `linspace` different from `arange`?)*

In [10]:
# TODO 1.5
np.linspace(0,2,num=9)
# DIFFERENCE: ...

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

**1.6** Create: (a) an array of 6 zeros, (b) a 3×4 array of ones, (c) a 3×3 array filled entirely with the number 7.

In [11]:
# TODO 1.6
a = np.zeros(6)
b = np.ones((3,3))
c1=np.arange(1,7)
c2=c1.reshape((2,3))
print(c2)
c =np.ones_like(c2)
print(a); print(b); print(c)

[[1 2 3]
 [4 5 6]]
[0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]]


**1.7** Create a 4×4 matrix of random integers between 1 and 50.

In [12]:
# TODO 1.7  (hint: np.random.randint(low, high, size))
matr4x4=np.random.randint(1,50,size=(4,4))

matr4x4

array([[39, 29, 15, 43],
       [ 8, 21, 39, 19],
       [23, 11, 11, 24],
       [36, 40, 24,  3]], dtype=int32)

In [13]:
matr4x4[2:,2:]

array([[11, 24],
       [24,  3]], dtype=int32)

In [14]:
matr4x4[1,2]

np.int32(39)

**1.8** Run `np.random.seed(0)` then `np.random.rand(3)`. Run the same two lines again in the cell below. Are the numbers the same? Why does that matter?

In [15]:
# TODO 1.8
np.random.seed(0)
rand1=np.random.rand(3)
print(rand1)

np.random.seed(0)
rand2=np.random.rand(3)
print(rand2)
# WHY IT MATTERS: ...

[0.5488135  0.71518937 0.60276338]
[0.5488135  0.71518937 0.60276338]


---
## Part 2 — Attributes and reshaping

In [16]:
# Use this array for Part 2
data = np.arange(1, 25)
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

**2.1** Print the `shape`, `size`, `ndim` and `dtype` of `data`.

In [17]:
# TODO 2.1
print("shape:", data.shape)
print("size :", data.size)
print("ndim :", data.ndim)
print("dtype:", data.dtype)

shape: (24,)
size : 24
ndim : 1
dtype: int64


**2.2** Reshape `data` into a 4×6 matrix.

In [18]:
# TODO 2.2
data4x6=data.reshape((4,6))

data4x6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

**2.3** Reshape `data` into a matrix with 3 rows, letting NumPy work out the number of columns automatically.

In [19]:
# TODO 2.3  (hint: the -1 trick)
data3=np.

data3

SyntaxError: invalid syntax (4152785032.py, line 2)

**2.4** Try reshaping `data` into a 5×5 matrix. It will fail — run it, read the error, and explain in one line why it cannot work.

In [20]:
# TODO 2.4  (this SHOULD produce an error)
dta5=data.reshape((5,5))
# WHY IT FAILS: ...
#cannot reshape array of size 24 into shape (5,5)
#array operation work is based upon matrix operation and we know that 'data' cannot be equally distributed in 5x5 so error occur 

ValueError: cannot reshape array of size 24 into shape (5,5)

**2.5** For the array `scores` below, find the maximum value, the minimum value, and the **position** (index) of each.

In [21]:
scores = np.array([45, 88, 62, 91, 30, 77, 55, 99, 40, 68])

In [22]:
# TODO 2.5
print("max     :", scores.max())
print("min     :", scores.min())
print("max at  :", scores.argmax())
print("min at  :", scores.argmin())

max     : 99
min     : 30
max at  : 7
min at  : 4


---
## Part 3 — Measures of central tendency

**3.1** For the array `temps` below, compute the mean **manually** (sum divided by count), then check it against the built-in `.mean()`.

In [23]:
temps = np.array([31, 35, 29, 33, 38, 30, 34])

In [24]:
# TODO 3.1
manual = sum(temps)/len(temps)
print("manual  :", manual)
print("built-in:", temps.mean())

manual  : 32.857142857142854
built-in: 32.857142857142854


**3.2** Compute the median of `temps`.

In [25]:
# TODO 3.2
np.median(temps)

np.float64(33.0)

**3.3** NumPy has no mode function. Use `scipy.stats` to find the mode of the array below.

In [26]:
grades = np.array([3, 7, 7, 2, 7, 5, 3, 7, 5])

In [27]:
# TODO 3.3
from scipy import stats
stats.mode(grades)

ModeResult(mode=np.int64(7), count=np.int64(4))

**3.4 — The outlier experiment.** Below are 10 house prices (in lakhs). Compute the mean and median. Then append one mansion priced at 5000 and recompute both. Which measure moved more?

In [28]:
prices = np.array([45, 52, 48, 61, 55, 43, 58, 50, 47, 53])

In [29]:
# TODO 3.4
print("BEFORE → mean:",prices.mean(), " median:", np.median(prices))

with_mansion = np.append(prices,5000)              # hint: np.append
print("AFTER  → mean:", with_mansion.mean(), " median:",np.median(with_mansion))

# WHICH MOVED MORE, AND WHY: ...
#mean moved more because the average increase occur in one one the value increase the value of other as well

BEFORE → mean: 51.2  median: 51.0
AFTER  → mean: 501.09090909090907  median: 52.0


**3.5** Below are 20 monthly salaries in thousands. Compute the mean and median, then write one sentence saying which better represents a typical employee — and why.

In [30]:
salaries = np.array([42, 38, 45, 50, 41, 39, 47, 44, 52, 40,
                     43, 46, 38, 49, 41, 45, 39, 48, 44, 950])

In [31]:
# TODO 3.5
print("mean  :", salaries.mean())
print("median:", np.median(salaries))
# ANSWER: ...
#when one constituent of the whole team salaries increase so it increase the total average salary 
#while the median remain bow down to all other value present highly in count just a little bit to average

mean  : 89.05
median: 44.0


---
## Part 4 — Array operations

**4.1 — The aliasing trap.** Run the cell below and explain what happened to `original`.

In [32]:
original = np.arange(10)
original

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
window = original[0:5]
window

array([0, 1, 2, 3, 4])

In [34]:
window[:] = 999

In [35]:
original = np.arange(10)
window = original[0:5]
window[:] = 999
print("original:", original)
# WHAT HAPPENED: ...
#original array was created with value 
#
#
#

original: [999 999 999 999 999   5   6   7   8   9]


**4.2** Repeat 4.1, but this time make sure `original` stays untouched.

In [36]:
# TODO 4.2
original = np.arange(10)
safe = ...                 # hint: .copy()
safe[:] = 999
print("safe    :", safe)
print("original:", original)

TypeError: 'ellipsis' object does not support item assignment

**4.3** Given `nums` below: append the values `[10, 11]`, insert `99` at index 2, and delete the element at index 0. Print each result.

In [47]:
nums = np.array([3, 1, 4, 1, 5])

In [43]:
# TODO 4.3
print("appended:", np.append(nums,[10,11]))
print("inserted:", np.insert(nums,2,99))
print("deleted :", np.delete(nums,0))

appended: [ 3  1  4  1  5 10 11]
inserted: [ 3  1 99  4  1  5]
deleted : [1 4 1 5]


**4.4** Sort `nums` in ascending order without changing the original array.

In [48]:
# TODO 4.4
print("sorted  :", np.sort(nums))
print("original:", nums)

sorted  : [1 1 3 4 5]
original: [3 1 4 1 5]


**4.5** Combine `a` and `b` below into one array. Then combine the two matrices `m1` and `m2` two ways: stacked as rows, and stacked side by side as columns.

In [49]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
m1 = np.ones((2, 3))
m2 = np.zeros((2, 3))

In [54]:
# TODO 4.5
print("joined 1D:", np.append(a,b))
print("as rows:\n", np.append(m1,m2,axis=0))          # hint: axis=0
print("as columns:\n", np.append(m1,m2,axis=1))       # hint: axis=1

joined 1D: [1 2 3 4 5 6]
as rows:
 [[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
as columns:
 [[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]


**4.6** Split the array `np.arange(12)` into 3 equal parts.

In [56]:
# TODO 4.6
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

---
## Challenge (optional)

**C.1** Create a 5×5 matrix of random integers from 1 to 100. Then print: the largest value, the smallest value, and the mean of the whole matrix.

In [58]:
# TODO C.1
matr=np.random.randint(1,100,size=(5,5))
matr

array([[80, 48, 65, 83, 89],
       [50, 30, 20, 20, 15],
       [40, 33, 66, 10, 58],
       [33, 32, 75, 24, 36],
       [76, 56, 29, 35,  1]], dtype=int32)

In [61]:
matr.max()

np.int32(89)

In [62]:
matr.min()

np.int32(1)

In [63]:
matr.mean()

np.float64(44.16)

In [68]:
import scipy

**C.2** A student's marks in 6 subjects are `[78, 85, 62, 91, 70, 88]`.
Compute the mean, then report **how far above or below the mean** each subject was.
*(Hint: subtracting a single number from an array applies it to every element.)*

In [70]:
# TODO C.2
marks = np.array([78, 85, 62, 91, 70, 88])
mean_mark = marks.mean()
differences = marks.std()
print("mean:", mean_mark)
print("differences:", differences)

mean: 79.0
differences: 10.263202878893768


**C.3** Two shops record their daily sales for a week. Which shop has the higher average? Which shop is more *consistent* — and how could you tell using only what you learned today?

In [71]:
shop_a = np.array([120, 118, 125, 122, 119, 121, 123])
shop_b = np.array([60, 200, 90, 180, 75, 195, 48])

In [77]:
# TODO C.3
print("Shop A mean:", shop_a.std())
print("Shop B mean:", shop_b.std())
# WHICH IS MORE CONSISTENT, AND HOW CAN YOU TELL: ...
print("Shop A mean:", np.median(shop_a))
print("Shop B mean:", np.median(shop_b))

Shop A mean: 2.2314999074019015
Shop B mean: 62.47840443231695
Shop A mean: 121.0
Shop B mean: 90.0


---
