# Week 4 · Day 2 — Exercises: Indexing, Broadcasting, Dispersion & Z-Scores

Practice for selection, boolean masks, broadcasting, universal functions, variance, standard deviation and z-scores.

**How to work:**
- Fill in each cell where you see `...` or a `# TODO`.
- Run your cell and check the output makes sense before moving on.
- When finished: `Kernel → Restart & Run All`

Setup — run this first.

In [1]:
import numpy as np
np.random.seed(42)

---
## Part 1 — Indexing and slicing

In [2]:
# Use this array for Part 1
arr = np.arange(10, 26)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

**1.1** Print the first element, the last element, and the elements from index 3 up to (but not including) index 8.

In [3]:
# TODO 1.1
print("first :", arr[0])
print("last  :", arr[-1])
print("3 to 8:", arr[:][3:8])

first : 10
last  : 25
3 to 8: [13 14 15 16 17]


**1.2** Print every **second** element of `arr`, and then `arr` reversed.

In [5]:
# TODO 1.2
print("every 2nd:", arr[:][0::2])
print("reversed :", arr[:][-1::-1])

every 2nd: [10 12 14 16 18 20 22 24]
reversed : [25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


**1.3** Using the matrix `mat` below, extract:
(a) the element in row 2, column 3
(b) the entire row 1
(c) the entire column 4
(d) the block made of rows 1–2 and columns 2–4

In [7]:
mat = np.arange(1, 31).reshape(5, 6)
mat

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [21]:
# TODO 1.3
print("(a)", mat[:,2])
print("(b)", mat[0,:])
print("(c)", mat[:,3])
print("(d)\n", mat[:2,2:5])

(a) [ 3  9 15 21 27]
(b) [1 2 3 4 5 6]
(c) [ 4 10 16 22 28]
(d)
 [[ 3  4  5]
 [ 9 10 11]]


---
## Part 2 — Boolean selection

This is the pattern behind every filter you will write in Pandas, so spend real effort here.

In [8]:
scores = np.array([45, 88, 62, 91, 30, 77, 55, 99, 40, 68, 73, 85])

**2.1** Create the boolean **mask** for "score is greater than 70" — do not filter yet, just show the True/False array.

In [9]:
# TODO 2.1
mask = scores>70
mask

array([False,  True, False,  True, False,  True, False,  True, False,
       False,  True,  True])

**2.2** Now use that mask to show only the scores above 70.

In [10]:
# TODO 2.2
scores[mask]

array([88, 91, 77, 99, 73, 85])

**2.3** Show all scores **between 50 and 90** (inclusive of neither end).
*(Remember: each condition needs its own parentheses.)*

In [ ]:
scores[(scores>50) & (scores<90)]

array([88, 62, 77, 55, 68, 73, 85])

In [20]:
# TODO 2.3
mask1=scores>50

In [21]:
mask2=scores<90 

In [22]:
scores[mask1]

array([88, 62, 91, 77, 55, 99, 68, 73, 85])

In [23]:
scores[mask2]

array([45, 88, 62, 30, 77, 55, 40, 68, 73, 85])

**2.4** Show all scores that are either **below 40 or above 95**.

In [24]:
# TODO 2.4  (hint: the | operator means OR)
scores[(scores<40)|(scores>95)]

array([30, 99])

**2.5** Run the cell below. It will fail. Read the error and explain in one line what is wrong, then write the corrected version.

In [25]:
40<scores|95>scores

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [26]:
# This SHOULD fail
a=scores[(scores > 50) & (scores < 90)]
np.size(a)

7

In [54]:
a

array([88, 62, 77, 55, 68, 73, 85])

In [ ]:
# TODO 2.5 — corrected version
...
# WHAT WAS WRONG: ...

**2.6** How **many** scores are above 70? Count them without listing them.
*(Hint: `True` counts as 1 when summed.)*

In [27]:
# TODO 2.6
mask3=scores>70
scores[mask3].size

6

In [28]:
mask3

array([False,  True, False,  True, False,  True, False,  True, False,
       False,  True,  True])

**2.7** Show all values in the matrix `mat` (from Part 1) that are **greater than the matrix's own mean**.

In [29]:
mat

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [30]:
mat.mean()

np.float64(15.5)

In [31]:
# TODO 2.7
mat[(mat)>(mat.mean())]


array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

---
## Part 3 — Broadcasting, casting and universal functions

**3.1** Given `prices` below (in rupees), apply a **10% discount** to every price in one line.

In [32]:
prices = np.array([1200, 850, 2300, 599, 1750])

In [33]:
# TODO 3.1
discprice=(prices)-(prices*0.1)
print(prices)
print(discprice)

[1200  850 2300  599 1750]
[1080.   765.  2070.   539.1 1575. ]


**3.2** Add a fixed delivery charge of 150 to every price, then square every result.

In [34]:
# TODO 3.2
with_delivery = discprice+150
print(with_delivery)
print(with_delivery**2)

[1230.   915.  2220.   689.1 1725. ]
[1512900.    837225.   4928400.    474858.81 2975625.  ]


**3.3** Convert the float array below to integers. What happened to the decimal parts — were they rounded?

In [35]:
vals = np.array([1.9, 2.5, 3.7, 4.2])

In [36]:
# TODO 3.3
np.int16(vals)
# WHAT HAPPENED: ...
# no they were not rounde
# but counverted to the integer below decimal point  

array([1, 2, 3, 4], dtype=int16)

**3.4** Apply `np.sqrt`, `np.log` and `np.abs` to the appropriate arrays below.

In [37]:
squares = np.array([4, 16, 25, 81, 100])
mixed = np.array([-5, 3, -8, 12, -1])


In [38]:
# TODO 3.4
print("square roots:", np.sqrt(squares))
print("natural log :", np.log(squares))
print("absolute    :", np.abs(mixed))

square roots: [ 2.  4.  5.  9. 10.]
natural log : [1.38629436 2.77258872 3.21887582 4.39444915 4.60517019]
absolute    : [ 5  3  8 12  1]


**3.5** Run the division below. It does not crash — explain what `inf` and `nan` mean here.

In [39]:
x = np.array([10.0, 5.0, 0.0])
y = np.array([2.0, 0.0, 0.0])
# TODO 3.5
np.divide(x,y)
# WHAT inf AND nan MEAN: ...
#inf=>division by zero error encountered
# nan invalid valid or null value in the first 

C:\Users\hp\AppData\Local\Temp\ipykernel_4224\3913917546.py:4: RuntimeWarning: divide by zero encountered in divide
  np.divide(x,y)
C:\Users\hp\AppData\Local\Temp\ipykernel_4224\3913917546.py:4: RuntimeWarning: invalid value encountered in divide
  np.divide(x,y)


array([ 5., inf, nan])

---
## Part 4 — Variance and standard deviation

**4.1** Two classes sat the same test. Compute the mean of each — you should find they are identical.

In [40]:
class_a = np.array([68, 70, 72, 69, 71])
class_b = np.array([40, 100, 55, 95, 60])

In [41]:
# TODO 4.1
print("Class A mean:", class_a.mean())
print("Class B mean:", class_b.mean())
print("Standard deviation :", class_a.std())
print("Standard deviation :", class_b.std())
print(np.median(class_a))
np.median(class_b)

Class A mean: 70.0
Class B mean: 70.0
Standard deviation : 1.4142135623730951
Standard deviation : 23.45207879911715
70.0


np.float64(60.0)

**4.2** Compute the variance of `class_b` **manually**, following the four steps: deviations → squared → averaged. Then check against the built-in `.var()`.

In [42]:
# TODO 4.2
deviations = class_b.std()
squared = np.square(deviations)
manual_var = squared

print("manual  :", manual_var)
print("built-in:", class_b.var())

manual  : 550.0000000000001
built-in: 550.0


**4.3** Compute the standard deviation of both classes. Explain in one line what the difference tells you that the mean did not.

In [43]:
# TODO 4.3
print("Class A std:", class_a.std())
print("Class B std:", class_b.std())
# WHAT THIS TELLS US: ...
#standard deviation is the method to analyze data that upto which extinct lower and higher a value 
# present in the total data provided by average  

Class A std: 1.4142135623730951
Class B std: 23.45207879911715


**4.4** Compute the **coefficient of variation** (std ÷ mean) for the two arrays below. Which quantity varies proportionally more, even though its raw numbers are much smaller?

In [44]:
salaries = np.array([50000, 60000, 45000, 70000, 55000])
heights  = np.array([160, 172, 168, 155, 180])

In [45]:
# TODO 4.4
cv_salaries = salaries.std()/salaries.mean()
cv_heights = heights.std()/heights.mean()
print("CV salaries:", round(cv_salaries, 4))
print("CV heights :", round(cv_heights, 4))
# WHICH VARIES MORE: ...

CV salaries: 0.1536
CV heights : 0.0527


**4.5** Compute the standard deviation of `class_b` two ways: with `ddof=0` (the NumPy default) and with `ddof=1`. Note that Pandas defaults to `ddof=1`, so the same data can show slightly different numbers in the two libraries.

In [47]:
import pandas as pd

In [49]:
# TODO 4.5
print("ddof=0 (NumPy default):", )
print("ddof=1 (Pandas default):", np.std(class_b))

ddof=0 (NumPy default):
ddof=1 (Pandas default): 23.45207879911715


---
## Part 5 — Z-scores, percentiles and quartiles

**5.1** For the exam scores below, compute the z-score of every student.
*(The formula is `(value − mean) ÷ std` — broadcasting doing statistics.)*

In [50]:
exam = np.array([55, 62, 78, 91, 45, 88, 70, 66, 82, 59])

In [54]:
# TODO 5.1
z = [(i-(exam.mean())/exam.std()) for i in exam ]
np.round(z, 2)

array([50.11, 57.11, 73.11, 86.11, 40.11, 83.11, 65.11, 61.11, 77.11,
       54.11])

**5.2** A student scored **91**. What is their z-score, and what does that number mean in plain words?

In [53]:
# TODO 5.2
z_91 = exam[3]-(exam.mean()/exam.std())
print(round(z_91, 2))
# MEANING: ...

86.11


**5.3** Compute the 25th, 50th and 75th percentiles of `exam`. Then compute the median separately and confirm it matches one of them.

In [58]:
# TODO 5.3
print("Q1    :", np.percentile(exam,25))
print("Q2    :", np.percentile(exam,50))
print("Q3    :", np.percentile(exam,75))
print("median:", np.median(exam))
# WHICH ONE MATCHES: ...

Q1    : 59.75
Q2    : 68.0
Q3    : 81.0
median: 68.0


**5.4** Compute the **interquartile range** (IQR) of `exam` — that is, Q3 minus Q1. Half of all students fall inside this range.

In [60]:
# TODO 5.4
q1, q3 = (np.percentile(exam,75)),(np.percentile(exam,25))
print("IQR:",q1-q3)

IQR: 21.25


**5.5** Generate 200 simulated exam scores with `np.random.normal(65, 12, 200)` (mean 65, std 12). Then compute the sample mean and std.
Are they exactly 65 and 12? Explain why not.

In [72]:
# TODO 5.5
np.random.seed(0)
sim = np.random.normal(65,12,200)
print("mean:", sim.mean())
print("std :", sim.std())
# WHY NOT EXACT: ...

mean: 65.85092591769393
std : 12.257073224351945


In [79]:
sim

array([86.16862815, 69.8018865 , 76.74485581, 91.89071839, 87.41069588,
       53.27266544, 76.40106101, 63.1837135 , 63.76137378, 69.92718202,
       66.72852285, 82.45128208, 74.1324527 , 66.4601002 , 70.32635879,
       69.00409193, 82.92894888, 62.53810083, 68.75681242, 54.75085113,
       34.36412221, 72.84342315, 75.37323439, 56.09401976, 92.23705549,
       47.5476119 , 65.54910221, 62.7537938 , 83.39335057, 82.63230524,
       66.85936911, 69.53795024, 54.34657103, 41.23044238, 60.82505421,
       66.87618763, 79.76348817, 79.42855819, 60.35207819, 61.37236699,
       52.41736442, 47.95978475, 44.52475771, 88.40930474, 58.88417382,
       59.74310838, 49.96645568, 74.32988427, 45.63322583, 62.44711664,
       54.25440127, 69.64282997, 58.87033835, 50.83241379, 64.66181326,
       70.13998245, 65.79820667, 68.62966277, 57.38813488, 60.64710601,
       56.93047463, 60.68536206, 55.24224462, 44.28460877, 67.12911371,
       60.17862877, 45.43761984, 70.55338707, 54.11241963, 65.62

---
## Challenge (optional)

**C.1** For the exam scores in Part 5, find how many students scored **more than one standard deviation above** the mean.
*(Combine a z-score calculation with a boolean mask.)*

In [73]:
std=exam.std()
mean=exam.mean()
count=np.sum(exam>(mean+std))
print(count)

2


In [81]:
# TODO C.1

z=exam>1
np.sum(z)

np.int64(10)

**C.2** Two shops' daily sales are given below. Using the standard deviation, decide which shop is more **consistent**, and by roughly how many times.

In [82]:
shop_a = np.array([120, 118, 125, 122, 119, 121, 123])
shop_b = np.array([60, 200, 90, 180, 75, 195, 48])

In [84]:
# TODO C.2
print("Shop A: mean", shop_a.mean(), "std", shop_a.std())
print("Shop B: mean", shop_b.mean(), "std", shop_b.std())
# CONCLUSION: ...
# shop a is more consistent because it standard deviation and median value have very less difference from the mean valu
# while shopb maybe depending upon the season or it will be not opening it shop on time to get much consistency 

Shop A: mean 121.14285714285714 std 2.2314999074019015
Shop B: mean 121.14285714285714 std 62.47840443231695


**C.3** Given the marks below, replace every score that is **more than 2 standard deviations from the mean** with the median.
*(This is a simple outlier-handling technique you will meet again when cleaning real data.)*

In [85]:
marks = np.array([72, 68, 75, 70, 5, 74, 71, 69, 98, 73])

In [91]:
marks.mean()

np.float64(67.5)

In [98]:
[marks>[(marks.mean()+marks.std())] &marks<[(marks.mean()-marks.std())]]

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [90]:
marks.std()

np.float64(22.375209496225953)

In [99]:
# TODO C.3
z = 2*marks.std()
outliers = np.abs(marks-marks.mean())>z         # a boolean mask
print("outliers found:", marks[outliers])

cleaned = marks.copy()
cleaned[outliers] = np.median(marks)
print("cleaned:", cleaned)

outliers found: [5]
cleaned: [72 68 75 70 71 74 71 69 98 73]


---